import type { Issue } from './types';

export const ERROR_SYNC_UNSUPPORTED = 'Shape is async, use tryAsync, parseAsync, or parseOrDefaultAsync.';
export const ERROR_SHAPE_EXPECTED = 'Provider must return a shape. Are you accessing a lazy shape prematurely?';
export const ERROR_ASYNC_FUNCTION = 'The function signature is constrained by async shapes, use ensureAsync.';

export const CODE_ANY_DENY = 'any.deny';
export const CODE_ANY_EXCLUDE = 'any.exclude';
export const CODE_ANY_REFINE = 'any.refine';
export const CODE_ARRAY_INCLUDES = 'array.includes';
export const CODE_ARRAY_MIN = 'array.min';
export const CODE_ARRAY_MAX = 'array.max';
export const CODE_BIGINT_MIN = 'bigint.min';
export const CODE_BIGINT_MAX = 'bigint.max';
export const CODE_DATE_MIN = 'date.min';
export const CODE_DATE_MAX = 'date.max';
export const CODE_NUMBER_FINITE = 'number.finite';
export const CODE_NUMBER_INT = 'number.int';
export const CODE_NUMBER_GT = 'number.gt';
export const CODE_NUMBER_GTE = 'number.gte';
export const CODE_NUMBER_LT = 'number.lt';
export const CODE_NUMBER_LTE = 'number.lte';
export const CODE_NUMBER_MULTIPLE_OF = 'number.multipleOf';
export const CODE_OBJECT_ALL_KEYS = 'object.allKeys';
export const CODE_OBJECT_NOT_ALL_KEYS = 'object.notAllKeys';
export const CODE_OBJECT_OR_KEYS = 'object.orKeys';
export const CODE_OBJECT_XOR_KEYS = 'object.xorKeys';
export const CODE_OBJECT_OXOR_KEYS = 'object.oxorKeys';
export const CODE_OBJECT_EXACT = 'object.exact';
export const CODE_OBJECT_PLAIN = 'object.plain';
export const CODE_SET_MIN = 'set.min';
export const CODE_SET_MAX = 'set.max';
export const CODE_STRING_NON_BLANK = 'string.nonBlank';
export const CODE_STRING_MIN = 'string.min';
export const CODE_STRING_MAX = 'string.max';
export const CODE_STRING_REGEX = 'string.regex';
export const CODE_STRING_INCLUDES = 'string.includes';
export const CODE_STRING_STARTS_WITH = 'string.startsWith';
export const CODE_STRING_ENDS_WITH = 'string.endsWith';
export const CODE_TYPE_ARRAY = 'type.array';
export const CODE_TYPE_BIGINT = 'type.bigint';
export const CODE_TYPE_BOOLEAN = 'type.boolean';
export const CODE_TYPE_CONST = 'type.const';
export const CODE_TYPE_DATE = 'type.date';
export const CODE_TYPE_ENUM = 'type.enum';
export const CODE_TYPE_FUNCTION = 'type.function';
export const CODE_TYPE_INSTANCE_OF = 'type.instanceOf';
export const CODE_TYPE_INTERSECTION = 'type.intersection';
export const CODE_TYPE_MAP = 'type.map';
export const CODE_TYPE_NEVER = 'type.never';
export const CODE_TYPE_NUMBER = 'type.number';
export const CODE_TYPE_OBJECT = 'type.object';
export const CODE_TYPE_PROMISE = 'type.promise';
export const CODE_TYPE_TUPLE = 'type.tuple';
export const CODE_TYPE_SET = 'type.set';
export const CODE_TYPE_STRING = 'type.string';
export const CODE_TYPE_SYMBOL = 'type.symbol';
export const CODE_TYPE_UNION = 'type.union';

export const MESSAGE_ANY_DENY = (issue: Issue) => 'Must not be equal to ' + issue.param;
export const MESSAGE_ANY_EXCLUDE = 'Must not conform the excluded shape';
export const MESSAGE_ANY_REFINE = 'Must conform the predicate';
export const MESSAGE_ARRAY_INCLUDES = 'Must include a value';
export const MESSAGE_ARRAY_MAX = (issue: Issue) => 'Must have the maximum length of ' + issue.param;
export const MESSAGE_ARRAY_MIN = (issue: Issue) => 'Must have the minimum length of ' + issue.param;
export const MESSAGE_BIGINT_MIN = (issue: Issue) => 'Must be greater than or equal to ' + issue.param;
export const MESSAGE_BIGINT_MAX = (issue: Issue) => 'Must be less than or equal to ' + issue.param;
export const MESSAGE_DATE_MIN = (issue: Issue) => 'Must be after ' + issue.param;
export const MESSAGE_DATE_MAX = (issue: Issue) => 'Must be before ' + issue.param;
export const MESSAGE_NUMBER_FINITE = 'Must be a finite number';
export const MESSAGE_NUMBER_INT = 'Must be an integer';
export const MESSAGE_NUMBER_GT = (issue: Issue) => 'Must be greater than ' + issue.param;
export const MESSAGE_NUMBER_GTE = (issue: Issue) => 'Must be greater than or equal to ' + issue.param;
export const MESSAGE_NUMBER_LT = (issue: Issue) => 'Must be less than ' + issue.param;
export const MESSAGE_NUMBER_LTE = (issue: Issue) => 'Must be less than or equal to ' + issue.param;
export const MESSAGE_NUMBER_MULTIPLE_OF = (issue: Issue) => 'Must be a multiple of ' + issue.param;
export const MESSAGE_OBJECT_ALL_KEYS = (issue: Issue) => 'Must contain all or no keys: ' + issue.param;
export const MESSAGE_OBJECT_NOT_ALL_KEYS = (issue: Issue) => 'Must contain not all or no keys: ' + issue.param;
export const MESSAGE_OBJECT_OR_KEYS = (issue: Issue) => 'Must contain at least one key: ' + issue.param;
export const MESSAGE_OBJECT_XOR_KEYS = (issue: Issue) => 'Must contain exactly one key: ' + issue.param;
export const MESSAGE_OBJECT_OXOR_KEYS = (issue: Issue) => 'Must contain one or no keys: ' + issue.param;
export const MESSAGE_OBJECT_EXACT = (issue: Issue) => 'Must not have unknown keys: ' + issue.param;
export const MESSAGE_OBJECT_PLAIN = 'Must be a plain object';
export const MESSAGE_SET_MIN = (issue: Issue) => 'Must have the minimum size of ' + issue.param;
export const MESSAGE_SET_MAX = (issue: Issue) => 'Must have the maximum size of ' + issue.param;
export const MESSAGE_STRING_NON_BLANK = 'Must not be blank';
export const MESSAGE_STRING_MIN = (issue: Issue) => 'Must have the minimum length of ' + issue.param;
export const MESSAGE_STRING_MAX = (issue: Issue) => 'Must have the maximum length of ' + issue.param;
export const MESSAGE_STRING_REGEX = (issue: Issue) => 'Must match the pattern ' + issue.param;
export const MESSAGE_STRING_INCLUDES = (issue: Issue) => 'Must include: ' + issue.param;
export const MESSAGE_STRING_STARTS_WITH = (issue: Issue) => 'Must start with: ' + issue.param;
export const MESSAGE_STRING_ENDS_WITH = (issue: Issue) => 'Must end with: ' + issue.param;
export const MESSAGE_TYPE_ARRAY = 'Must be an array';
export const MESSAGE_TYPE_BIGINT = 'Must be a bigint';
export const MESSAGE_TYPE_BOOLEAN = 'Must be a boolean';
export const MESSAGE_TYPE_CONST = (issue: Issue) => 'Must be equal to ' + issue.param;
export const MESSAGE_TYPE_DATE = 'Must be a Date';
export const MESSAGE_TYPE_ENUM = (issue: Issue) => 'Must be equal to one of ' + issue.param.join(', ');
export const MESSAGE_TYPE_FUNCTION = 'Must be a function';
export const MESSAGE_TYPE_INSTANCE_OF = 'Must be a class instance';
export const MESSAGE_TYPE_INTERSECTION = 'Intersection results are incompatible';
export const MESSAGE_TYPE_MAP = 'Must be a Map';
export const MESSAGE_TYPE_NEVER = 'Must not be used';
export const MESSAGE_TYPE_NUMBER = 'Must be a number';
export const MESSAGE_TYPE_OBJECT = 'Must be an object';
export const MESSAGE_TYPE_PROMISE = 'Must be a Promise';
export const MESSAGE_TYPE_TUPLE = (issue: Issue) => 'Must be a tuple of length ' + issue.param;
export const MESSAGE_TYPE_SET = 'Must be a Set';
export const MESSAGE_TYPE_STRING = 'Must be a string';
export const MESSAGE_TYPE_SYMBOL = 'Must be a symbol';
export const MESSAGE_TYPE_UNION = 'Must conform the union';
